#<% require 'kitchen-sync' %>
#<% time = Time.new.strftime("%F %H:%M") %>
---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  environments_path: environments
  roles_path: roles
  data_bags_path: test/fixtures/data_bags

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: test_w_haproxy_master
    driver:
      vm_hostname: "haproxy01"
      network:
        - ["private_network", {ip: "172.31.1.12"}]
    run_list:
      - recipe[w_common::default]
      - recipe[w_haproxy::default]
    attributes: {
     "haproxy": {
      "enable_ssl": true
     },
     "keepalived": {
       "global": {
        "router_id": "haproxy01"
       },
       "instances": {
         "vi_1": {
           "priorities": "101",
           "interface": "eth1"
         }
       }
     }
    }
  - name: test_w_haproxy_backup
    #driver:
      #vm_hostname: "haproxy02"
      #network:
      #  - ["private_network", {ip: "172.31.1.13"}]
    run_list:
      - recipe[w_haproxy::default]
    attributes: {
     "keepalived": {
       "global": {
        "router_id": "haproxy02"
       },
       "instances": {
        "vi_1": {
          "priorities": "100",
          "interface": "eth1"
        }
       }
     }
    }
